languageCode = "es-es"
title = "Functional Programming"
theme = ["github.com/dzello/reveal-hugo"]

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[module]
[[module.imports]]
    path = 'github.com/dzello/reveal-hugo'