languageCode = "es-es"
title = "Functional Programming"
theme = "reveal-hugo"

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[module]
[[module.imports]]
    path = 'https://github.com/dzello/reveal-hugo'